language: python
python:
- '3.6'
script:
- python ./setup.py test
notifications:
  slack:
    secure: OcyVs8BydqyXQQFlyVbOyZZ4D4kHem1vb4yLeX1c2aHwAIQQ/ZacnymC8UUVkXARq+luRz6PCqVE6NEdk4XuoqR42miBkHKc5CvU4RJJzZ+xx6FGGzKuJAmfXA8+IH89dBMENzrpmQwtZPSMi2K5sUfSBykP4G6Ief+fb+uC/lm0/RzkidTD7lFXMWaIUmUR4TDsTw47Lk/XSq13E7Q8jL7UE0A5939IcKAf74pelFUQbZ/haG+q74BAt193F/OxYOdIMvVHaRth016WWsT6+ZClVvkahjkzp5zvR2N00hPcUIGTqkRs6NMY/TuOjUYj2pRIaN7oktqVaPtkLQCvr6kFWXvTOgnQCIw7sp/Wdvs5Ym9rXeJUqxtWlVV+BuY+x7WSQ+JcJxUgEKcGWXXpcijyqVWrALBxvb9X52onlAxz9x4YOeS6RpIWJQntGHcLlxqiGRN5Yvy7bwL2bxKQL4daTKJCaCpR/YGAofZyo3+WpsuvhG1zdmMKoxxqJxabaTXXHUDI8HX2xnwlgAcEmzLH2UoIg2NIQ7+gF/5QASf2XhMkPrWJFK7VHKbrApXoJ2b8sdpuItQxTVOVCEQNqQlHYEo4Y5ymGtmA71CPv3yz8rE2hg1ctAtZpkD3PKjTLHmBTs8+c/PZedZNqRekFEE9x3Di3Tk135QYwSSKKGU=
